# Generated by Django 4.0.6 on 2022-07-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_transferencia', models.CharField(max_length=15)),
                ('conta_origem', models.CharField(max_length=10)),
                ('conta_destino', models.CharField(max_length=10)),
                ('valor', models.FloatField()),
                ('data_transferencia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_conta', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('PF', 'Fisica'), ('PJ', 'Juridica')], default='PF', max_length=2)),
                ('cpf', models.CharField(max_length=11, null=True, unique=True)),
                ('cnpj', models.CharField(max_length=14, null=True, unique=True)),
                ('nome', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=200)),
                ('saldo_atual', models.FloatField(default=0)),
                ('data_registro', models.DateField()),
            ],
        ),
    ]
